add failure

diff --git a/.github/workflows/audit.yml b/.github/workflows/audit.yml
--- a/.github/workflows/audit.yml
+++ b/.github/workflows/audit.yml
@@ -29,16 +29,21 @@ jobs:
         id: check_vulnerabilities
         run: cargo audit
         continue-on-error: true
-
-      - name: Audit Failure
-        if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
+      - if: failure()
         uses: sarisia/actions-status-discord@v1
         with:
           webhook: ${{ secrets.DISCORD_WEBHOOK }}
-          description: "Audit Failure"
-          nocontext: false
+          nocontext: true
           avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
 
-      - name: Final status
-        if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
-        run: exit 1
+      # - name: Audit Failure
+      #   if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
+      #   uses: sarisia/actions-status-discord@v1
+      #   with:
+      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
+      #     nocontext: true
+      #     avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
+
+      # - name: Final status
+      #   if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
+      #   run: exit 1
